package syrincs.c_adapters.postgres;

import syrincs.a_domain.rhythm.HuffmanRhythm;
import syrincs.b_application.AppDefaults;
import syrincs.b_application.ports.RhythmRepository;

import java.sql.*;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

/**
 * Postgres implementation of the RhythmRepository.
 *
 * Adapts HuffmanRhythm persistence to the Postgres table "public.huffmanRhythms" with columns:
 *   id BIGINT PRIMARY KEY,
 *   rhythmstring VARCHAR(100),
 *   numerator SMALLINT NOT NULL,
 *   denominator SMALLINT NOT NULL,
 *   info SMALLINT NOT NULL,
 *   deviation DOUBLE PRECISION
 */
public class PostgresRhythmRepository implements RhythmRepository {

    private final String url;
    private final String user;
    private final String password;

    public PostgresRhythmRepository(String url, String user, String password) {
        this.url = url;
        this.user = user;
        this.password = password;
    }

    private Connection getConnection() throws SQLException {
        return DriverManager.getConnection(url, user, password);
    }

    @Override
    public List<Long> saveAll(List<HuffmanRhythm> rhythms) {
        Objects.requireNonNull(rhythms, "rhythms must not be null");
        if (rhythms.isEmpty()) return Collections.emptyList();

        // We do not insert the id column here; assume it's generated by the database (IDENTITY/SEQUENCE)
        String sql = "INSERT INTO public.huffmanRhythms (rhythmstring, numerator, denominator, info, deviation) VALUES (?,?,?,?,?)";
        final int batchSize = 1024;
        List<Long> ids = new ArrayList<>(rhythms.size());

        try (Connection con = getConnection();
             PreparedStatement ps = con.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {

            con.setAutoCommit(false);

            int count = 0;
            for (HuffmanRhythm r : rhythms) {
                ps.setString(1, r.getOnsetList());
                ps.setInt(2, r.getNumerator());
                ps.setInt(3, r.getDenominator());
                ps.setInt(4, r.getInformation());
                ps.setDouble(5, r.getStandardDeviation());
                ps.addBatch();
                count++;

                if (count % batchSize == 0) {
                    ps.executeBatch();
                    try (ResultSet rs = ps.getGeneratedKeys()) {
                        while (rs.next()) {
                            ids.add(rs.getLong(1));
                        }
                    }
                }
            }

            if (count % batchSize != 0) {
                ps.executeBatch();
                try (ResultSet rs = ps.getGeneratedKeys()) {
                    while (rs.next()) {
                        ids.add(rs.getLong(1));
                    }
                }
            }

            con.commit();
        } catch (SQLException e) {
            throw new RuntimeException("Failed to batch save HuffmanRhythms", e);
        }
        return ids;
    }

    @Override
    public List<HuffmanRhythm> getTwoRhythms(Integer id1, Integer id2) {
        Objects.requireNonNull(id1, "id1 must not be null");
        Objects.requireNonNull(id2, "id2 must not be null");
        String sql = "SELECT id, rhythmstring, numerator, denominator FROM public.huffmanRhythms WHERE id = ANY(?)";
        List<HuffmanRhythm> out = new ArrayList<>(2);
        try (Connection con = getConnection(); PreparedStatement ps = con.prepareStatement(sql)) {
            Long[] arr = new Long[] { id1.longValue(), id2.longValue() };
            Array sqlArr = con.createArrayOf("int8", arr);
            ps.setArray(1, sqlArr);
            Map<Long, HuffmanRhythm> byId = new HashMap<>();
            try (ResultSet rs = ps.executeQuery()) {
                while (rs.next()) {
                    long id = rs.getLong("id");
                    String onset = rs.getString("rhythmstring");
                    int numerator = rs.getInt("numerator");
                    int denominator = rs.getInt("denominator");
                    // Domain HuffmanRhythm requires tempo; DB doesn't store it. Use application default tempo.
                    HuffmanRhythm r = new HuffmanRhythm(numerator, denominator, AppDefaults.DEFAULT_TEMPO_BPM, onset);
                    byId.put(id, r);
                }
            }
            // Ensure output order corresponds to requested ids and duplicates allowed
            HuffmanRhythm r1 = byId.get(id1.longValue());
            if (r1 != null) out.add(r1);
            HuffmanRhythm r2 = byId.get(id2.longValue());
            if (r2 != null) out.add(r2);
        } catch (SQLException e) {
            throw new RuntimeException("Failed to load two HuffmanRhythms by id", e);
        }
        return out;
    }

    @Override
    public List<HuffmanRhythm> getAllByInformation(Integer information) {
        Objects.requireNonNull(information, "information must not be null");
        String sql = "SELECT rhythmstring, numerator, denominator FROM public.huffmanRhythms WHERE info = ? ORDER BY id";
        List<HuffmanRhythm> result = new ArrayList<>();
        try (Connection con = getConnection(); PreparedStatement ps = con.prepareStatement(sql)) {
            ps.setInt(1, information);
            try (ResultSet rs = ps.executeQuery()) {
                while (rs.next()) {
                    String onset = rs.getString("rhythmstring");
                    int numerator = rs.getInt("numerator");
                    int denominator = rs.getInt("denominator");
                    result.add(new HuffmanRhythm(numerator, denominator, AppDefaults.DEFAULT_TEMPO_BPM, onset));
                }
            }
        } catch (SQLException e) {
            throw new RuntimeException("Failed to load HuffmanRhythms by information", e);
        }
        return result;
    }

    @Override
    public List<HuffmanRhythm> getAllByInformationAndMinDeviation(Integer information, Double minDeviation){
        Objects.requireNonNull(information, "information must not be null");
        Objects.requireNonNull(minDeviation, "minDeviation must not be null");
        String sql = "SELECT rhythmstring, numerator, denominator FROM public.huffmanRhythms WHERE info = ? AND deviation > ? ORDER BY id";
        List<HuffmanRhythm> result = new ArrayList<>();
        try (Connection con = getConnection(); PreparedStatement ps = con.prepareStatement(sql)) {
            ps.setInt(1, information);
            ps.setDouble(2, minDeviation);
            try (ResultSet rs = ps.executeQuery()) {
                while (rs.next()) {
                    String onset = rs.getString("rhythmstring");
                    int numerator = rs.getInt("numerator");
                    int denominator = rs.getInt("denominator");
                    result.add(new HuffmanRhythm(numerator, denominator, AppDefaults.DEFAULT_TEMPO_BPM, onset));
                }
            }
        } catch (SQLException e) {
            throw new RuntimeException("Failed to load HuffmanRhythms by information and minimum deviation", e);
        }
        return result;
    }
}
