package syrincs.c_adapters.postgres;

import syrincs.a_domain.rhythm.HuffmanRhythm;
import syrincs.b_application.ports.RhythmRepository;

import java.sql.*;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Objects;

/**
 * Postgres implementation of the RhythmRepository.
 *
 * Adapts HuffmanRhythm persistence to the Postgres table "public.huffmanRhythms" with columns:
 *   id BIGINT PRIMARY KEY,
 *   rhythmstring VARCHAR(100),
 *   numerator SMALLINT NOT NULL,
 *   denominator SMALLINT NOT NULL,
 *   info SMALLINT NOT NULL
 */
public class PostgresRhythmRepository implements RhythmRepository {

    private final String url;
    private final String user;
    private final String password;

    public PostgresRhythmRepository(String url, String user, String password) {
        this.url = url;
        this.user = user;
        this.password = password;
    }

    private Connection getConnection() throws SQLException {
        return DriverManager.getConnection(url, user, password);
    }

    @Override
    public List<Long> saveAll(List<HuffmanRhythm> rhythms) {
        Objects.requireNonNull(rhythms, "rhythms must not be null");
        if (rhythms.isEmpty()) return Collections.emptyList();

        // We do not insert the id column here; assume it's generated by the database (IDENTITY/SEQUENCE)
        String sql = "INSERT INTO public.huffmanRhythms (rhythmstring, numerator, denominator, info) VALUES (?,?,?,?)";
        final int batchSize = 1024;
        List<Long> ids = new ArrayList<>(rhythms.size());

        try (Connection con = getConnection();
             PreparedStatement ps = con.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {

            con.setAutoCommit(false);

            int count = 0;
            for (HuffmanRhythm r : rhythms) {
                ps.setString(1, r.getOnsetList());
                ps.setInt(2, r.getNumerator());
                ps.setInt(3, r.getDenominator());
                ps.setInt(4, r.getInformation());
                ps.addBatch();
                count++;

                if (count % batchSize == 0) {
                    ps.executeBatch();
                    try (ResultSet rs = ps.getGeneratedKeys()) {
                        while (rs.next()) {
                            ids.add(rs.getLong(1));
                        }
                    }
                }
            }

            if (count % batchSize != 0) {
                ps.executeBatch();
                try (ResultSet rs = ps.getGeneratedKeys()) {
                    while (rs.next()) {
                        ids.add(rs.getLong(1));
                    }
                }
            }

            con.commit();
        } catch (SQLException e) {
            throw new RuntimeException("Failed to batch save HuffmanRhythms", e);
        }
        return ids;
    }
}
