package syrincs.c_adapters.runtime;

import org.junit.jupiter.api.Test;

import java.util.List;

import static org.junit.jupiter.api.Assertions.assertTrue;

class LocalRuntimeTest {

    @Test
    void schemaStatementsContainApplicationTablesAndRhythmColumns() {
        List<String> statements = LocalRuntime.schemaStatements();
        String schema = String.join("\n", statements);

        assertTrue(schema.contains("hindemithChords"));
        assertTrue(schema.contains("huffmanRhythms"));
        assertTrue(schema.contains("rhythmstring"));
        assertTrue(schema.contains("deviation"));
        assertTrue(schema.contains("GENERATED BY DEFAULT AS IDENTITY"));
    }
}
